id: 5d5dfb1e-29d8-4568-bfa3-f7e4caad5163444
name: Secret added to entra id application
version: 1.0.0
kind: Scheduled
description: |-
  A new secret was added to an entra id application.

  Can contain false positives if a secret was deleted but there is still another secret present
severity: High
queryFrequency: 30m
queryPeriod: 30m
triggerOperator: gt
triggerThreshold: 0
tactics:
  - CredentialAccess
  - Persistence
query: |+
  AuditLogs
  | where OperationName has "Update application – Certificates and secrets management"
  | where Result == "success"
  | project InitiatedBy, TargetResources, ActivityDisplayName, TimeGenerated
  | extend a=parse_json(InitiatedBy)
  | extend user=a.user.userPrincipalName
  | extend b = parse_json(TargetResources)
  | extend res=b[0].displayName
  | extend property=b[0].modifiedProperties[0]
  | project user, res, property, ActivityDisplayName, TimeGenerated
suppressionEnabled: false
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: 5h
    matchingMethod: AllEntities
    groupByEntities: []
    groupByAlertDetails: []
    groupByCustomDetails: []
eventGroupingSettings:
  aggregationKind: AlertPerResult
customDetails:
  Application: ActivityDisplayName
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: FullName
        columnName: user
suppressionDuration: 5h
